[package]
name = "malevolence"
authors = ["fawn <fawn@envs.net>"]
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.171", features = ["derive"] }
